version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - INSTANCE_HOST=db
      - DB_USER=test
      - DB_PASS=test
      - DB_NAME=test
      - DB_PORT=5432
    ports:
      - 5000:5000

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
